app = "helpdesk-system-app" # Можешь изменить имя на своё уникальное
primary_region = "fra"     # Франкфурт (ближайший регион)

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  DB_PATH = "/data/helpdesk.db"

[mounts]
  source = "helpdesk_data"
  destination = "/data"